### ISSUE TITLE
not possible to connect to native TranslateLocally application

### ISSUE THREAD

**Issue by cadeyrn** [jelmervdl/translatelocally-web-ext#53]
I can't select the locally installed TranslateLocally application within the add-on's settings. The option is greyed out:

<img width="517" alt="Bildschirm­foto 2022-11-03 um 22 07 52" src="https://user-images.githubusercontent.com/1100614/199834458-c274ed14-2b1a-4957-b2cf-dcf665d512bf.png">

What I did:

1. I installed the M1/M2 version from https://translatelocally.com/ on my MacBook Pro with M1 Pro and macOS 13.
2. I started the application.
3. I installed the webextension version 0.7.2 from https://addons.mozilla.org/en-US/firefox/addon/translatelocally-for-firefox/ in Firefox Nightly (108a1, 2022-11-03).
4. I opened the add-on's settings on about:addons.

The browser console shows an error message that could be relevant:

`ExtensionError: No such native application translatelocally`

**Comment by jelmervdl** [comment]
Hi @cadeyrn,

Could you try downloading the latest TranslateLocally build from Github and do the steps with that one? I think its this build you'd need: https://github.com/XapaJIaMnu/translateLocally/releases/download/latest/translateLocally.macos-11.0.x86-64.dmg

What might have happened is that the extension id for _TranslateLocally for Firefox_ recently changed because I had to republish it to make it public. I fixed that in TranslateLocally the desktop edition as well, but I'm not sure whether those changes made it all the way to the website.

**Comment by cadeyrn** [comment]
Unfortunately it does not work with this version either.

**Comment by cadeyrn** [comment]
@jelmervdl I did a few more tests, these are my results:

- Apple M1 based, macOS 13, TranslateLocally from website - does **not** work
- Apple M1 based, macOS 13, TranslateLocally from GitHub - does **not** work
- Apple Intel based, macOS 12.5, TranslateLocally from GitHub - does **not** work
- Windows 11 via Parallels on Apple M1, TranslateLocally from website - does **not** work
- Windows 11 via Parallels on Apple M1, TranslateLocally from GitHub - does **work**

Conclusions:

- The version from the website is outdated, but that's probably a topic for the issues tracker of the desktop application
- Native messaging works on Windows, but not on macOS, neither on M1 based nor on Intel based devices
- It's not a new issue with macOS 13 since it doesn't work on macOS 12 as well

**Comment by jelmervdl** [comment]
@cadeyrn Thank you for testing this!

I can now replicate this. It looks like as if that build for some reason doesn't write the manifest files. I don't know why, but I either suspect a sandboxing issue on macOS, or just a bug in the mac version of TranslateLocally. I'll have to look a bit deeper into it, but this is definitely a bug in TranslateLocally.

I'll close the issue here and follow up on it on the TranslateLocally repository.
