### ISSUE TITLE
translation popup should either close or show success once translation is complete

### ISSUE THREAD

**Issue by cadeyrn** [jelmervdl/translatelocally-web-ext#54]
Right now the translation popup keeps open once the translations is complete and still shows the progress bar and the "stop translating" button. As the button can be used to show the original text it makes sense to still show the button. But the button label "stop translating" in combination with the fact that nothing else changes in the popup can be a bit misleading as it feels as the translation is still in progress.

So my proposal is to either close the popup or to do _something_ in the panel to indicidate that the translation progress is complete. One idea would be to change the button label to something like "show original text".

**Comment by jelmervdl** [comment]
This is a good point. Technically it is this way because it is in a "state of translation" where any updates to the page will be translated as they occur. But from a user's point of view, if there's no translations pending, it should show as done.

I also agree that "Stop Translating" is not accurate anymore. "Show original" is a better label for the button because regardless of how far the page has progressed translating, that's what the effect of that button is.

There is a brief moment between you asking for a translation and the translation starting where the model is downloaded etc. There the text "Stop translating" makes more sense since the entire page is still the original page.

I'm going to change it to:
- Replace the progress bar with "Translation complete" text when there are no more pending translations. As soon as the page changes and there are more elements to translate, we can replace that label again with the progress bar.
- Replace the button text with "Show Original" once one bit of the page has been translated.
