### ISSUE TITLE
Q: what's the difference between this ext. and the one by Mozilla?

### ISSUE THREAD

**Issue by atomGit** [jelmervdl/translatelocally-web-ext#59]
hi Jelmer - i'm just curious; what's the difference between your extension and the [one by Mozilla](https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/)?

the supported languages seem to be the same and both appear to be using the same resource for translations

**Comment by jelmervdl** [comment]
The README mentions some of it, but I'll expand a bit on it here.

The gist is: same translation engine, but the extension around it is developed slightly different. Some of the features made it into Mozilla's extension at some point, but I've kept developing my fork after that.

## Differences from _Firefox Translations_
- Uses models from https://github.com/browsermt/students. Most of these are also available through Mozilla's extension.  
Mozilla imported most of these models (as they were trained for them as part of the Bergamot project) but also trained more on their own (which they mark as "beta"). I expect the list I use will grow once the [HPLT project](https://hplt-project.org) gets underway. I don't know what Mozilla's plans are for supporting more languages, or improving the quality of their models.
- UI is a button + popup instead of the translation bar because the translation bar is not available for unprivileged extensions.  
The UI of my version is a bit less obstructive. No big bar.
- More seamless webpage translation.  
I've continued development of the webpage translation bit (that translates web apps as you interact with them), fixing bugs that I discovered after I last contributed back to Mozilla's copy of that component. I've also added a feature to restore the original page content without having to reload, which makes it feasible to continuously toggle between the translated page and the original one.
- Translation of selection  
For when you don't need the entire page translate for you. Select some text, right click, get a translation. Simply a feature missing from Mozilla's extension.
- Translation engine and memory is shared among all tabs and webpages  
Mozilla's version has the translator run in the process of the page itself. From a security standpoint this might be better, as pages cannot affect each other through the translator. The downside however is that every time you navigate to a new page, the translator has to restart, load the model, and start translating from scratch. I found the performance win of sharing one translator (and translation cache!) across pages to be worth the potential risk of a page trying to perform a timing attack. I'm planning on restricting translation caches to web page origins to further reduce that risk.
- Removed optional translation quality indicators  
Mozilla has the option to turn on these squiggly lines in translations it isn't certain about. However I'm also quite uncertain about how the model decides which translations it is uncertain about. And the squiggles aren't really actionable. Nor does it really explain what it is uncertain about. I'm also doubtful the models coming from HPLT will have support for that feature.
- UI is only in English ([for now](https://github.com/jelmervdl/translatelocally-web-ext/issues/43))  
I haven't had the time or manpower to provide translations for the extension itself, hehe.
- Option to use the desktop version of TranslateLocally as translation engine.  
That desktop app is running native code (not WASM) and can use the hardware far more efficient than the WASM runtime can. Downside is that you have to install additional software and it doesn't work in all scenarios (due to different sandboxing techniques per operating system…)
- No telemetry of any kind.

**Comment by atomGit** [comment]
interesting - thanks for the detailed description!

regarding shared memory across tabs - that seems like it might be a concern - for example if the user enables network partitioning (privacy.firstparty.isolate), might this negate that? or break translation in another tab? ... i haven't used either add-on yet, but if the overhead in not sharing this memory is only a few hundred ms, i don't think anyone would complain

regarding quality indicators - assuming that feature remains, i think this could be valuable even if no context is provided - my thinking here is that some translations of particular words are purposely inaccurate in order to mislead the reader

**Comment by cadeyrn** [comment]
Hi and thank you for for all the details!

> I've continued development of the webpage translation bit (that translates web apps as you interact with them), fixing bugs that I discovered after I last contributed back to Mozilla's copy of that component.

I don't know if it's appropriate to ask this since you're maintaining your own extension with TranslateLocally. But since you know Firefox Translations very well would you consider contributing improvements / bug fixes to the webpage translation bit of Firefox Translations as well? Or is the code base already very different from each other? Maybe you don't want to, which would be understandable, but I thought it doesn't cost anything to ask. I like both extensions very much. :)

**Comment by jelmervdl** [comment]
Hey @atomGit,

> regarding shared memory across tabs - that seems like it might be a concern - for example if the user enables network partitioning (privacy.firstparty.isolate), might this negate that? or break translation in another tab? ... i haven't used either add-on yet, but if the overhead in not sharing this memory is only a few hundred ms, i don't think anyone would complain

There's no directly shared memory between tabs. All tabs just send translation requests to the same translation worker. If you want to make tabs read memory from one another, you'll have to find a way to communicate through response times to translation messages.

I think `privacy.firstparty.isolate` only applies to cookies etc. However, if you configure firefox in such a way that it runs isolated profiles for different websites, I think extensions  are part of a profile, so you'd end up running multiple copies of the extensions as well. Which then would not share their translation memory among each other. But I haven't tried any of this.

> i haven't used either add-on yet, but if the overhead in not sharing this memory is only a few hundred ms, i don't think anyone would complain

You'd be surprised how much memory this add-on actually eats, I'm afraid 😅 The loaded wasm runtime + transformer model uses quite a chunk of memory.

One way to measure it yourself: go to https://translatelocally.com/web/. Then also open about:memory and measure the memory usage of that tab. Now start typing in the translation box on that page (which will trigger it to load) and measure again.

> my thinking here is that some translations of particular words are purposely inaccurate in order to mislead the reader

Quality estimation isn't advanced in any way. I think roughly it is based on how likely a certain word sequence is according to the translation model. Or even more roughly, how similar a produced translation sequence is to data the model has seen during training. I dug a bit through the commit history (this was all done before I joined the project) and I think [the implementation](https://github.com/browsermt/bergamot-translator/commit/63120c174e3edfd664175d4a2be095d8b50a112f) is doing what is described in [this paper](https://arxiv.org/abs/2005.10608). In a way, I'm maybe more worried about the false sense of confidence they give in parts that are not marked as inaccurate. It would be fairly simple to trick the translation model to produce a wrong translation that it is very confident about precisely because of how it prefers to produce translations that match what it has seen during training.

**Comment by jelmervdl** [comment]
Hi @cadeyrn,

> I don't know if it's appropriate to ask this since you're maintaining your own extension with TranslateLocally. But since you know Firefox Translations very well would you consider contributing improvements / bug fixes to the webpage translation bit of Firefox Translations as well? 

I've done this a couple of times in the past, but relations between University of Edinburgh and Mozilla have broken down a bit since the project ended. I've been active in their Github issues, diagnosing bugs and proposing fixes that are related to parts I wrote. But they don't seem to engage at all. I get the impression that they're mostly in maintenance mode for the moment.
