### ISSUE TITLE
Native Messaging detect 0.7.1+

### ISSUE THREAD

**Issue by VladimirChalanov** [jelmervdl/translatelocally-web-ext#62]
Hi,

I am using translateLocally version v0.0.2+136745e
I installed this from the Arch User Repository (found this way on translatelocally.com).
It works fine.

translateLocally create file /home/USERNAME/.mozilla/native-messaging-hosts/translatelocally.json

`{
    "allowed_extensions": [
        "{c9cdf885-0431-4eed-8e18-967b1758c951}"
    ],
    "description": "Fast and secure translation on your local machine, powered by marian and Bergamot.",
    "name": "translatelocally",
    "path": "/usr/bin/translateLocally",
    "type": "stdio"
}`

I also use an addon. Firefox addon version higher than 0.7.1 doesn't work on my system (translateLocally choice is not available). I tried Firefox Developer Edition (for use unsigned addon), it doesn't work either.

Version 0.7.1 downloaded from the addons.mozilla.org does not work.
translateLocally 0.7.1 downloaded from github works well, but requires internet to display addon menu.

Is there a problem with the addon or my installation?

**Comment by jelmervdl** [comment]
Oh hmm, ironically that isn't a scenario I've tested thoroughly.

Ideally it should indeed, but the extension does ask translateLocally for a model list including the models that aren't downloaded. That request might be failing because translateLocally can't access the remote model list. I'll look into it.

**Comment by jelmervdl** [comment]
I'll close this issue for now. I've moved the offline issue to upstream.

TranslateLocally is used by us to demonstrate research and make it more widely available. I think at least the desktop software will stay funded/around for a while. This extension isn't directly funded atm, and I'm mostly maintaining it because I enjoy it. So its future is a little less certain.
