### ISSUE TITLE
Auto select source language

### ISSUE THREAD

**Issue by yukulele** [jelmervdl/translatelocally-web-ext#67]
### Reproduce steps:
- enable "Never offer translations" option
- open a page to translate
- open the translate page tool

### Expected result:
current page language should be selected as source language

### Actual result: 
source language is not selected:
![Screenshot_20230314_215824](https://user-images.githubusercontent.com/347244/225134741-6f59674c-d157-4525-ab6c-e67395cc3be6.png)

**Comment by jelmervdl** [comment]
Hi @yukulele 

By the looks of it, you're using [the Mozilla extension](https://github.com/mozilla/firefox-translations), not mine 😅. Could you please report the issue to them?

When you do, also mention the page you're experiencing this on. I think this happens when the extension doesn't recognise the language of the page (which is most likely a bug), or when it is in a language not supported yet by the extension.
